# Site settings
title: Presteigne Chess Club
email: kevin.saull@mypostoffice.co.uk
weekday: Tuesdays
meetingtime: 7.30pm
venue: "Radnorshire Arms"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: pretty
url: "http://presteignechess.club" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
paginate: 5
exclude: [templates, node_modules, bower_components, bower.json, gulpfile.js, Gemfile, Gemfile.lock, unused_assets]
prose:
  ignore:
    - .gitignore
    - CNAME
    - Gemfile
    - Gemfile.lock
    - apple-touch-icon.png
    - archive.html
    - favicon.ico
    - google045fc8195b06d68a.html
    - robots.txt
    - _config.yml
    - /_layouts
    - /_includes
    - /unused_assets
    - /css
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
          help: "You do not need to worry about hyphenating the title here."
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: "CURRENT_DATETIME"
      - name: "categories"
        field:
          element: "multiselect"
          options:
            - name: News
              value: news
          label: "Categories"
          help: "Add one or more categories here. Select from the dropdown or add new."
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: "true"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "Kevin"
          help: Author Name (Kevin by default)
          type: text

# Gems
gems: [jekyll-paginate]