# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

email: brianjbutcher65@gmail.com
description: An experimental web site template for a Presteigne Chess Club
baseurl: "" # the subpath of your site, e.g. /blog

# Chess Club specific variables - set these to values for your club

title: Presteigne Chess Club
url: "http://presteignechess.club" # the base hostname & protocol for your site, e.g. http://example.com
clubname: Presteigne Chess Club
clubsecretary: Dave Hancock
secretaryphone:  01544598416
secretaryemail: 
webmaster: brianjbutcher65@gmail.com

# Menu bar display options - true is you want item displayed on menu bar
show-features: false
show-fixtures: true
show-members: false
show-opinion: false
show-admin_notes: true

# Homepage - club specific values
regular-meeting-info: We meet on Tuesday evenings at the Royal Oak in Presteigne
venue-link: ""
venue-picture: "assets/img/oak.jpg"
display-pgn-file: "pgn/classics.pgn" # FIXME This cannot be changed 

# The rest of this file concerns site structure - you are unlikely to want to change it
collections_dir: my_collections

collections:

  news:
    output: true

  features:
    output: true

  fixtures:
    output: true

  members:
    output: true

  opinion:
    output: true

  admin_notes:
    output: true

  pgn:
    output: true
  
# Build settings
markdown: kramdown

#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
